### ISSUE TITLE
[META] Ideas 💡

### ISSUE THREAD

**Issue by moul** [moul/captcha#1]
* [x] basic captcha -> ASCII banner (#2)
* [x] basic captcha -> simple math (#12)
* [x] random captcha (#12)
* [ ] example of web handler
* [ ] basic captcha -> advanced maths
* [ ] basic captcha -> questions
* [ ] basic captcha -> ASCII banner with random lines
* [ ] support custom pinentry program
* [ ] offline real captchas
* [ ] manual action, i.e., click on a yubikey
* [ ] real recaptcha (open a browser)
* [ ] chain captchas
* [ ] retry policy
* [ ] Libpam integration
* [ ] example of usage as a library
